[tool.poetry]
name = "skellycam"
version = "2023.09.1086"
description = "\"A simple python API for efficiently connecting to and recording synchronized videos from one or multiple cameras 💀📸\""
authors = ["Skelly FreeMoCap <info@freemocap.org>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.9, <3.12"
numpy = "^1.26.2"
opencv-contrib-python = "4.8.*"
pydantic = "<2"
matplotlib = "3.7.2"
pandas = "2.1.0"
pillow = "^10.0.1"
setproctitle = "^1.3.3"
tqdm = "^4.66.1"
scikit-image = "^0.22.0"
rich = "^13.6.0"
plotly = "^5.17.0"
blosc2 = "^2.2.9"
tabulate = "^0.9.0"
tzlocal = "^5.1"
pyside6 = "^6.5.3"
pyqtgraph = "^0.13.3"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
pre-commit = "^3.4.0"
pyinstaller = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[project.urls]
Homepage = "https://github.com/freemocap/skellycam"

[tool.bumpver]
current_version = "v2023.09.1086"

version_pattern = "vYYYY.0M.BUILD[-TAG]"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = true

[tool.bumpver.file_patterns]
"skellycam/__init__.py" = ["{version}"]

[project.scripts]
skellycam = "skellycam.__main__:main"

[tool.setuptools]
py-modules = ["skellycam"]




classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Other Audience",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Capture",
    "Topic :: Multimedia :: Video :: Display",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: System :: Hardware",
    "Topic :: System :: Hardware :: Universal Serial Bus (USB)",
    "Topic :: System :: Hardware :: Universal Serial Bus (USB) :: Video (UVC)",
    ]
keywords = [
    "camera",
    "stream",
    "video",
    "image",
    "opencv",
    "skelly",
    "freemocap",
    "motion capture",
    "synchronization",
    "computer vision"
]